n1 = float(input("Digite um número: "))
n2 = float(input("Digite o segundo número: "))
print("Adição", n1 + n2)
print("Subtração", n1 - n2)
print("Multiplicação", n1 * n2)
print("Divisão", n1 / n2)
print("Divisão inteira", n1 // n2)
print("Resto de divisão", n1 % n2)
print("potencia", n1 ** n2)